### ISSUE TITLE
Corrupted video_id for How2R train.

### ISSUE THREAD

**Issue by antoine77340** [ych133/How2R-and-How2QA#1]
Hi,

Thank you for the data!
There are some corrupted video_ids for How2R with video_ids set to "#NAME?".

Could you please update the csv? 

Thanks!

**Comment by ych133** [comment]
> Hi,
> 
> Thank you for the data!
> There are some corrupted video_ids for How2R with video_ids set to "#NAME?".
> 
> Could you please update the csv?
> 
> Thanks!

Yes, I will update it.

**Comment by antoyang** [comment]
There still is the same problem in the csv of How2QA. Also, there are multiple video ids that are 10 (and not 11) characters long (e.g. wY6tKv3uBg). Could you please update it?

**Comment by ych133** [comment]
> wY6tKv3uBg

The updated version resolved the "#NAME?" issue and also most of the 10-c ids issue. Please let me know if you find a few.

**Comment by antoyang** [comment]
@ych133 Thanks for updating. However, in the various csv of How2QA, it seems the following ids are still not 11-c long: ['bKDGQ_1CPakk', 'wY6tKv3uBg', 'Ze3QzH5H3c', 'mUa1PYhN20', 'mUa1PYhN20', 'nh7GGgUhDM', 'TlZwBdDWUE', 'TlZwBdDWUE', 'txBwtLFgRs', 'oMF9Ut2ZBQ', 'Oo8tHyXtQE', 'bNfgwPz', 'lISPkr0l28', 'pxkR8Sd35k', 'lISPkr0l28'].
