### ISSUE TITLE
Number of val and test exemples in How2QA

### ISSUE THREAD

**Issue by antoyang** [ych133/How2R-and-How2QA#2]
Hi,
It seems there are 35k train exemples, 2.8k val exemples and 2.9k test public exemples released in How2QA (so about 41K exemples). However, you mentioned in your paper that there are 44K QAs (80%/10%/10% train / val / test).
1) It seems there is a non-negligible part of val exemples not released. Could you please update the val release?
2) Do you plan to release an evaluation server for the test private?

Best,
Antoine Yang

**Comment by ych133** [comment]
> Hi,
> It seems there are 35k train exemples, 2.8k val exemples and 2.9k test public exemples released in How2QA (so about 41K exemples). However, you mentioned in your paper that there are 44K QAs (80%/10%/10% train / val / test).
> 
> 1. It seems there is a non-negligible part of val exemples not released. Could you please update the val release?
> 2. Do you plan to release an evaluation server for the test private?
> 
> Best,
> Antoine Yang

1. We held a small portion of data from Val/Test for the future release of the private-test set.  This does not affect the scores reported in Val/Test much.
2. We planned to release the private test set (not sure an evaluation server, maybe just a leaderboard to submit the model).

**Comment by antoyang** [comment]
Thanks for the answers. I have one other concern though: The tables 3 and 4 of the paper show results on test and val respectively. It looks like the R1, R5, R10 on How2R and the acc on How2QA are all unchanged between val and test. Is it right?

**Comment by ych133** [comment]
> Thanks for the answers. I have one other concern though: The tables 3 and 4 of the paper show results on test and val respectively. It looks like the R1, R5, R10 on How2R and the acc on How2QA are all unchanged between val and test. Is it right?

There is a miss alignment: Tables 3 and 4 both report test results. Table 5 is the val. We will update the arXiv version.
